version: '3'
services:
    # Postgres
    db:
        image: postgres:14-alpine
        hostname: db
        environment:
                POSTGRES_USER: "postgres"
                POSTGRES_PASSWORD: "docker"
                POSTGRES_DB: "postgres"
        ports:
            - "5432:5432"

    # Django
    web:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: web
        command: ./run_web.sh
        volumes:
            - .:/code:Z
        ports:
            - "8000:8000"
        links:
            - db
            - rabbit
            - redis
        depends_on:
            - db

    frontend:
        build:
          context: ../frontend
        image: node:18
        hostname: frontend
        command: npm run dev
        network_mode: "host"
        expose:
          - "3000"
        volumes:
          - /frontend/node_modules
          - ./frontend:/frontend

    # Redis
    redis:
        image: redis:3.2.8
        hostname: redis

    # RabbitMQ
    rabbit:
        hostname: rabbit
        image: rabbitmq:3.6.9
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "5672:5672"
            - "15672:15672"

    # Celery worker
    worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: ./run_celery.sh
        volumes:
            - .:/code:Z
        links:
            - db
            - rabbit
            - redis
        depends_on:
            - rabbit

    # Celery worker
    beat:
        build:
            context: .
            dockerfile: Dockerfile
        command: ./run_celery_beat.sh
        volumes:
            - .:/code:Z
        links:
            - worker
            - db
            - rabbit
            - redis
        depends_on:
            - worker
            - rabbit
